### PR TITLE
screenshots

### PR DESCRIPTION
**Pull request by berleant**
@orlando

### CODE REVIEW

**Comment by orlando** [comment]
@shoshber why this was merged if still needs work? Also, what are the advantages we have instead of just using the custom fields and signup fields Discourse provide. I thought this way it will look/work better

**Comment by berleant** [comment]
Y'all told me not to worry about the styling/looks. Other than that there's no more work to be done (aside from improving the feedback on the debt field/collective fields, which I noted in the pull request (https://github.com/debtcollective/new-user-plugin/pull/2) I might skip in the interest of time).

I, just like you, thought the best way to do this was with the built-in user fields at first, but I quickly ran into some inherent limitations. We did discuss this briefly before. Some of the limitations: Discourse accepts only three data types: "confirmation" (which is a checkbox), "text field", and "dropdown". There was no way to add our own validations, like "this field should only accept whole numbers" (e.g. for the debt amount) or "at least one collective must be selected". There's no way to specify that fields should be required in some cases and not required in others. There's no way to toggle the visibility of fields based on other answers. I expected we will want to have different styling for the collectives vs the other fields, and that would be difficult if they were built-in user fields. Those are just some reasons I can recall off the top of my head.

**Comment by orlando** [comment]
@shoshber I was expecting this to look usable in a default Discourse instance, I'll create another ticket as follow up for this one

**Comment by orlando** [comment]
This is the follow up ticket, https://github.com/debtcollective/parent/issues/134. Let's update the README with screenshots once that's fixed

I'll close this PR

**Pull request closed without merging**
